"""`claude-relay init` and `claude-relay uninstall`.

init:
  1. Create relay dirs.
  2. Migrate existing inbox messages to include new fields (read_at, edited_at,
     broadcast_id, archived) with null/False defaults.
  3. Install the skill at $HOME/.claude/skills/claude-relay/.
  4. Replace ~/.claude/relay/relay.py with a shim that dispatches to this CLI.

uninstall reverses 3 and 4. Data (#1, #2) is left in place."""
from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

import claude_relay
from ...core import paths


SHIM_TEMPLATE = """#!/usr/bin/env python3
# Auto-generated by `claude-relay init`. Re-creates the historical
# CLI path so any existing slash commands or skills that hardcode
# ~/.claude/relay/relay.py keep working.
import sys
from claude_relay.cli.__main__ import main
sys.exit(main())
"""


def _home() -> Path:
    import os
    return Path(os.environ.get("HOME", str(Path.home())))


def _packaged_skill_dir() -> Path:
    return Path(claude_relay.__file__).parent / "skill"


def _skill_install_dir() -> Path:
    return _home() / ".claude" / "skills" / "claude-relay"


def _migrate_message(p: Path) -> None:
    try:
        data = json.loads(p.read_text())
    except json.JSONDecodeError:
        return
    changed = False
    for k, default in (("read_at", None), ("edited_at", None),
                       ("broadcast_id", None), ("archived", False)):
        if k not in data:
            data[k] = default
            changed = True
    if changed:
        p.write_text(json.dumps(data, indent=2))


def run_init(force: bool = False) -> int:
    paths.ensure_dirs()
    # Migrate inbox + processed
    for base in (paths.INBOX_DIR, paths.PROCESSED_DIR):
        if not base.exists():
            continue
        for msg_path in base.rglob("*.json"):
            _migrate_message(msg_path)
    # Install skill
    target = _skill_install_dir()
    src = _packaged_skill_dir()
    if target.exists() and not force:
        print(f"skill already installed at {target} (use --force to overwrite)")
    else:
        if target.exists():
            shutil.rmtree(target)
        shutil.copytree(src, target)
        print(f"installed skill → {target}")
    # Install shim
    legacy = paths.RELAY_DIR / "relay.py"
    if not legacy.exists() or force or "Auto-generated by `claude-relay init`" not in legacy.read_text():
        legacy.write_text(SHIM_TEMPLATE)
        legacy.chmod(0o755)
        print(f"installed shim → {legacy}")
    print("init complete. try: claude-relay tui")
    return 0


def run_uninstall() -> int:
    target = _skill_install_dir()
    if target.exists():
        shutil.rmtree(target)
        print(f"removed skill {target}")
    legacy = paths.RELAY_DIR / "relay.py"
    if legacy.exists() and "Auto-generated by `claude-relay init`" in legacy.read_text():
        legacy.unlink()
        print(f"removed shim {legacy}")
    print("uninstall complete. data preserved at ~/.claude/relay/")
    return 0
